[package]
name = "migrations"
version.workspace      = true
edition.workspace      = true
authors.workspace      = true
license.workspace      = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "migrations"
path = "src/main.rs"

[dependencies]
sea-orm-migration.workspace = true
async-trait.workspace       = true
tokio.workspace             = true
