//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20
//! 手工新增（M2+I1+I2）：统一 Post 内容模型 + 身份中心 + 多租户表。

pub mod prelude;

// ── 现有（图片 CMS） ──────────────────────────────────────────
pub mod categories;
pub mod media_assets;
pub mod media_variants;
pub mod photo_tags;
pub mod photo_translations;
pub mod photos;
pub mod site_settings;
pub mod tags;
pub mod users;

// ── 统一内容模型（M2） ───────────────────────────────────────
pub mod post_meta;
pub mod post_revisions;
pub mod post_terms;
pub mod post_translations;
pub mod posts;
pub mod term_taxonomies;
pub mod terms;

// ── 租户 / 站点（I2 多租户） ─────────────────────────────────
pub mod site_domains;
pub mod sites;
pub mod tenants;

// ── 身份 / RBAC（I1） ────────────────────────────────────────
pub mod memberships;
pub mod permissions;
pub mod role_permissions;
pub mod roles;
pub mod site_grants;
pub mod user_credentials;
pub mod user_identities;
pub mod user_mfa;
pub mod user_profiles;

// ── 会话 / 令牌 / IdP / 审计（I3-I6） ────────────────────────
pub mod audit_logs;
pub mod oauth_authorization_codes;
pub mod oauth_clients;
pub mod oauth_consents;
pub mod refresh_tokens;
pub mod sessions;
pub mod signing_keys;
