//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "media_assets")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub storage_key: String,
    #[sea_orm(column_type = "Text")]
    pub mime_type: String,
    pub width: Option<i32>,
    pub height: Option<i32>,
    pub byte_size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub checksum_sha256: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub exif: Json,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::media_variants::Entity")]
    MediaVariants,
    #[sea_orm(has_many = "super::photos::Entity")]
    Photos,
}

impl Related<super::media_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaVariants.def()
    }
}

impl Related<super::photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Photos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
