//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "media_variants")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    pub asset_id: i64,
    #[sea_orm(column_type = "Text")]
    pub variant: String,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    pub width: i32,
    pub height: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_assets::Entity",
        from = "Column::AssetId",
        to = "super::media_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaAssets,
}

impl Related<super::media_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaAssets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
