//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "photos")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    pub category_id: Option<i64>,
    pub primary_asset_id: i64,
    #[sea_orm(column_type = "Text")]
    pub privacy: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub passcode_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub taken_at_label: String,
    pub taken_at_date: Option<Date>,
    pub uploaded_by: Option<i64>,
    pub sort_order: i64,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Categories,
    #[sea_orm(
        belongs_to = "super::media_assets::Entity",
        from = "Column::PrimaryAssetId",
        to = "super::media_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MediaAssets,
    #[sea_orm(has_many = "super::photo_tags::Entity")]
    PhotoTags,
    #[sea_orm(has_many = "super::photo_translations::Entity")]
    PhotoTranslations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UploadedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::media_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaAssets.def()
    }
}

impl Related<super::photo_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhotoTags.def()
    }
}

impl Related<super::photo_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhotoTranslations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::photo_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::photo_tags::Relation::Photos.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
