//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20（手工补充新表）

pub use super::categories::Entity as Categories;
pub use super::media_assets::Entity as MediaAssets;
pub use super::media_variants::Entity as MediaVariants;
pub use super::photo_tags::Entity as PhotoTags;
pub use super::photo_translations::Entity as PhotoTranslations;
pub use super::photos::Entity as Photos;
pub use super::site_settings::Entity as SiteSettings;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;

// 统一内容模型
pub use super::post_meta::Entity as PostMeta;
pub use super::post_revisions::Entity as PostRevisions;
pub use super::post_terms::Entity as PostTerms;
pub use super::post_translations::Entity as PostTranslations;
pub use super::posts::Entity as Posts;
pub use super::term_taxonomies::Entity as TermTaxonomies;
pub use super::terms::Entity as Terms;

// 租户 / 站点
pub use super::site_domains::Entity as SiteDomains;
pub use super::sites::Entity as Sites;
pub use super::tenants::Entity as Tenants;

// 身份 / RBAC
pub use super::memberships::Entity as Memberships;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::site_grants::Entity as SiteGrants;
pub use super::user_credentials::Entity as UserCredentials;
pub use super::user_identities::Entity as UserIdentities;
pub use super::user_mfa::Entity as UserMfa;
pub use super::user_profiles::Entity as UserProfiles;

// 会话 / 令牌 / IdP / 审计
pub use super::audit_logs::Entity as AuditLogs;
pub use super::oauth_authorization_codes::Entity as OauthAuthorizationCodes;
pub use super::oauth_clients::Entity as OauthClients;
pub use super::oauth_consents::Entity as OauthConsents;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::sessions::Entity as Sessions;
pub use super::signing_keys::Entity as SigningKeys;
