//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::categories::Entity as Categories;
pub use super::media_assets::Entity as MediaAssets;
pub use super::media_variants::Entity as MediaVariants;
pub use super::photo_tags::Entity as PhotoTags;
pub use super::photo_translations::Entity as PhotoTranslations;
pub use super::photos::Entity as Photos;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
