-- 回滚 M2+I1+I2。只删本迁移新增的表（不动现有 users/photos/categories/tags/media_*）。
-- 顺序：子表先于父表；用 CASCADE 兜底（RLS 策略随表删除）。

DROP TABLE IF EXISTS post_meta CASCADE;
DROP TABLE IF EXISTS post_revisions CASCADE;
DROP TABLE IF EXISTS post_terms CASCADE;
DROP TABLE IF EXISTS term_taxonomies CASCADE;
DROP TABLE IF EXISTS terms CASCADE;
DROP TABLE IF EXISTS post_translations CASCADE;
DROP TABLE IF EXISTS posts CASCADE;

DROP TABLE IF EXISTS audit_logs CASCADE;

DROP TABLE IF EXISTS oauth_consents CASCADE;
DROP TABLE IF EXISTS oauth_authorization_codes CASCADE;
DROP TABLE IF EXISTS oauth_clients CASCADE;

DROP TABLE IF EXISTS signing_keys CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;

DROP TABLE IF EXISTS site_grants CASCADE;
DROP TABLE IF EXISTS memberships CASCADE;
DROP TABLE IF EXISTS user_mfa CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS user_identities CASCADE;
DROP TABLE IF EXISTS user_credentials CASCADE;

DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

DROP TABLE IF EXISTS site_domains CASCADE;
DROP TABLE IF EXISTS sites CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
